version: '3.4'

networks:
  learn2save:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - learn2save
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: learn2save
      MYSQL_USER: username 
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./services/mysql/init:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - learn2save
    restart: always
    environment:
      PMA_ARTBITRARY: 1
      MYSQL_USER: username 
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8085:80
    links:
      - mysql:db
    depends_on:
      - mysql
